### ISSUE TITLE
'required' may not be working in modals for the `Select` section

### ISSUE THREAD

**Issue by smoneta** [yhatt/jsx-slack#222]
Hello team, Im working on a modal that have several required fields and inputs. I noticed that the required tag in the static select is not working since I submit without making a selection and dont get any warning.

```
<Modal title="Selection menu" close="Close" submit=Submit>
 <Section id="option_menu_selection">
    <b>What is the best option for you?</b>
        <Select placeholder="Select an item" name="Choose an option" required>
           <Option>
             Option 1
          </Option>  
              <Option>
             Option 2
          </Option> 
              <Option>
             Option 3
          </Option> 
    	</Select>
    </Section>
</Modal>
```
[link](https://jsx-slack.netlify.app/#jsx:eJyVkbEOwiAURWf7FTf8AFFXWgdn49DBsaHtMyWhRYEO_r1Q2mgTNZHlkcvlvMtDnEwrNbzymnJWkqbGKzOgp2FkaLRxQT7GwuDGulc-L6dSZBDlbFZtzswtbqt4r3ILhgVXWKIuLp30UA6-I9TkPJIfV2PxMONB8Dp5J3_KgZuWDXVGt2SXbJChnaeeYZB9jNaZkC2qCchg6T4qS-0LF4nn6XSlAUnE9k0VfHYCa-9vxO4j4h_C_jthI3h6_DxNPs-9yASfvq94AtmIfa0=)

Im putting the `required` tag in the wrong place?

**Comment by yhatt** [comment]
Yes. `required` must exist with `label` prop because it's a part of the input component. If you were setting up JSX transpiler, it should mark as error through red underline.

![input-components](https://user-images.githubusercontent.com/3993388/116253542-89518780-a7ab-11eb-97df-f7b677c99aec.png)

Slack Block Kit JSON cannot represent required select element in the accessory of section block cannot. `required` (= opposite of `optional` field in Block Kit JSON) is only for [input layout block](https://api.slack.com/reference/block-kit/blocks#input) so you have to use `<Input>` instead of `<Section>`.

```jsx
<Modal title="Selection menu" close="Close" submit="Submit">
  <Input label="What is the best option for you?" required>
    <Select placeholder="Select an item" name="Choose an option">
      <Option>Option 1</Option>  
      <Option>Option 2</Option> 
      <Option>Option 3</Option> 
    </Select>
  </Input>
</Modal>
```

And the following JSX is meaning same:

```jsx
<Modal title="Selection menu" close="Close" submit="Submit">
  <Select placeholder="Select an item" name="Choose an option"  label="What is the best option for you?" required>
    <Option>Option 1</Option>  
    <Option>Option 2</Option> 
    <Option>Option 3</Option> 
  </Select>
</Modal>
```

If represent required field in JSON, you would have to use either of them. Otherwise, you have to add validation logic in your app.

**Comment by smoneta** [comment]
Thanks!!
