### ISSUE TITLE
Empty space between blocks when making dynamic ones

### ISSUE THREAD

**Issue by smoneta** [yhatt/jsx-slack#223]
Hi team, I have a dynamic modal where some questions show not appear in case the object (where i build a multi select) is empty.  I notice that there is an extra space when the question shows up and can understand why, here is a sample of the js code:

```
const modal = (props) => {
    let user_selection_block = null
    if (props.users.length > 0) {
        let users_options = [];
        for (let i = 0; i < props.users.length; i++) {
            users_options.push(${props.users[i].name});
        }
        user_selection_block = jsxslack`
        <Section id="userSelection">
	        <b>Select one or more users:</b> (optional)
		        <Select placeholder="Click here to select" actionId="PrimeAESelect" multiple>
		        	>> another sub function that create the jsx options from the 'users_options' array <<
		        </Select>
        </Section>`
    }
    return jsxslack`
        <Textarea actionId="users" id="users_block" label="Please select users" required/>
        <CheckboxGroup id="modal_options" label="Check all the options which apply" actionId="modal_options" required>
        	>> Checkbox options <<
        </CheckboxGroup>
        ${user_selection_block}
        `;
};
```

When the array is empty the multi select question is not there and is fine, but when It does I see an empty space between the checkbox question and the multi select. is this on purpose? or im just missing something on the code?

I notice the space when the question is skipped but I assumed it was just the `user_selection_block` resolving to nothing.. but then the space is still when it resolves to the needed jsx block.

Thanks.

**Comment by yhatt** [comment]
Your jsx-slack code looks like no problems. Are you pointing out a "visible" gap between components?

[![](https://user-images.githubusercontent.com/3993388/119209109-ea852600-badf-11eb-9034-00e1a647dd55.png)][preview]

[Click to preview in Slack Block Kit Builder...][preview]

If so, this is not an issue of jsx-slack because it is about how Slack is styling space between components. We're not Slack, just a part of community.

[preview]: https://app.slack.com/block-kit-builder/#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22modal%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22blocks%22:%5B%7B%22type%22:%22input%22,%22block_id%22:%22users_block%22,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Please%20select%20users%22,%22emoji%22:true%7D,%22optional%22:false,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22users%22,%22multiline%22:true%7D%7D,%7B%22type%22:%22input%22,%22block_id%22:%22modal_options%22,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Check%20all%20the%20options%20which%20apply%22,%22emoji%22:true%7D,%22optional%22:false,%22element%22:%7B%22type%22:%22checkboxes%22,%22action_id%22:%22modal_options%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22test%22,%22verbatim%22:true%7D,%22value%22:%22test%22%7D%5D%7D%7D,%7B%22type%22:%22section%22,%22block_id%22:%22userSelection%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*Select%20one%20or%20more%20users:*%20(optional)%22,%22verbatim%22:true%7D,%22accessory%22:%7B%22type%22:%22multi_static_select%22,%22action_id%22:%22PrimeAESelect%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Click%20here%20to%20select%22,%22emoji%22:true%7D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22test%22,%22emoji%22:true%7D,%22value%22:%22test%22%7D%5D%7D%7D%5D%7D
