### ISSUE TITLE
preview adds submit button by default.. is a bug?

### ISSUE THREAD

**Issue by smoneta** [yhatt/jsx-slack#230]
When I create this modal in the JSX page..

```
<Modal title="Lead Pass Bot">
  <Image src="https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif" alt="something heading your way"/>             
</Modal>
```

I see this JSON on the right:

```
{
  "type": "modal",
  "title": {
    "type": "plain_text",
    "text": "Lead Pass Bot",
    "emoji": true
  },
  "blocks": [
    {
      "type": "image",
      "alt_text": "something heading your way",
      "image_url": "https://c.tenor.com/I6kN-6X7nhAAAAAj/loading-buffering.gif"
    }
  ]
}
```

which is OK I see that when I click PREVIEW adds the submit button in the block bit page is this intentional?

**Comment by yhatt** [comment]
Implicitly replacement seems to be happened after accesing Block Kit Builder. It always replaces even if using permalink generated by Block Kit Builder, not only jsx-slack.

I think it's a bug of Block Kit Builder, but _jsx-slack cannot do anything_ because I'm not a part of Slack. Please try to report that to Slack directly.

- https://api.slack.com/support
- https://my.slack.com/help/requests/new

**Comment by smoneta** [comment]
Thanks!
